version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "Admin#123456"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        restart: always

    sample:
        container_name: sample
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - '.:/app'
          - '/app/node_modules'
        ports:
          - '3001:3000'
        environment:
          - NODE_ENV=development